language: java
jdk: oraclejdk8

install: true

script:
  - mvn -Plinux-x86 clean validate compile package verify -DskipTests
  - mvn -Plinux-x86_64 clean validate compile package verify -DskipTests
  - mvn -Pmac-x86_64 clean validate compile package verify -DskipTests
  - mvn -Pwin32 clean validate compile package verify -DskipTests
  - mvn -Pwin64 clean validate compile package verify -DskipTests