name: Build Workflow

on: push

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci --verbose
      - run: npm run release

  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - run: echo "Ready to deploy to GitHub Pages."
