name: Build Workflow

on:
    push:
        branches:
          - "master"

jobs:
    build:
        name: Build Job
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: "12.x"
            - run: npm ci --verbose
            - run: npm run release
