name: Build Workflow

on: push

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci --verbose
      - run: npm run release
      - name: Upload test report artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: build/tests/index.html
      - name: Upload test coverage report artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: build/coverage/lcov-report
      - name: Upload app artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/dist

  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - run: echo "Ready to deploy to GitHub Pages."
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: app
      - run: cat index.html
